### ISSUE TITLE
Pick attributes without docstrings

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/pytkdocs#11]
Just like we still select objects with no docstrings, we could also pick attributes without docstrings.

The user can then configure the plugin to render them or not.

**Comment by ofek** [comment]
We very much need this 😄

**Comment by ofek** [comment]
Any update?

**Comment by pawamoy** [comment]
Sorry, nope, I've been working on other things. I'll try to work on this these next few days.

**Comment by ofek** [comment]
Has this been implemented?

**Comment by pawamoy** [comment]
Still not @ofek :sweat_smile: But I'm currently working on refactoring the attribute parser, which will make it easier to implement this feature :relaxed:

So, it's on the way!
