### ISSUE TITLE
Allow picking up inherited members for classes

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/pytkdocs#18]
See https://github.com/pawamoy/mkdocstrings/issues/78.

We should change

```python
for member_name, member in class_.__dict__.items():
```

...to

```python
for member_name, member in inspect.getmembers(class_):
```

...based on configuration options.

We must also distinguish inherited members from regular ones, to be able to apply different filters.

**Comment by rossmechanic** [comment]
@pawamoy when do you think this will be done?

**Comment by pawamoy** [comment]
I'm currently refactoring the attribute parser, and I'll be able to take care of this once it's done.

Also, I started working again, so I'll be way less available :confused: 

But I'll make this happen :slightly_smiling_face:

**Comment by tristanz** [comment]
Any progress on this item?  I'm looking at sphinx vs. mkdocs and this is the one blocking issue for us.

**Comment by pawamoy** [comment]
Not really! I didn't think work would be taking so much of my time and energy :confused: And I don't even have kids yet :sweat_smile:!

**Comment by pawamoy** [comment]
Work in progress now :slightly_smiling_face:

**Comment by ofek** [comment]
Yay!!!

**Comment by pawamoy** [comment]
I commented on https://github.com/pawamoy/mkdocstrings/issues/78
