### ISSUE TITLE
Allow ignoring objects

### ISSUE THREAD

**Issue by RDIL** [pawamoy/pytkdocs#40]
Sometimes, I want to document an entire tree, but not specific modules.  It would be nice if you could put something like `@pytkdocs-ignore` in the docstring and have pytkdocs, well, ignore it!  This would be nice and helpful in situations where I don't want documentation to appear for a specific class at all.

**Comment by pawamoy** [comment]
Isn't the `filters` option enough :slightly_smiling_face:?

**Comment by RDIL** [comment]
I'm not sure as to how to implement that for mkdocstrings...

**Comment by pawamoy** [comment]
You can set your filters in the YAML config. See [this example](https://github.com/pawamoy/mkdocstrings/issues/62#issuecomment-605290939).

I will write documentation once I finish refactoring the attributes parser.

**Comment by pawamoy** [comment]
I'll go ahead and close this one, please open a new issue if you have trouble using filters for your use case!
