### ISSUE TITLE
Incorrectly dedenting class documentation (non PEP-257-compliant)

### ISSUE THREAD

**Issue by jaredkhan** [pawamoy/pytkdocs#54]
Leading whitespace on class comments is not stripped correctly when the first line of text is on the same line as the triple-quotes.

A class like the following:
```
class A:
     """This is a class.
     
     More words here.
     """
     pass
```
ends up having whitespace stripped to look like this:

```
This is a class.

    More words here.
```

whereas this is expected:

```
This is a class.

More words here.
```

The intended behaviour is specified in [PEP-257: Docstring Conventions > Handling Docstring Indentation](https://www.python.org/dev/peps/pep-0257/#id18) and implemented in `inspect.cleandoc` (which is called by `inspect.getdoc`)

This is only a problem for classes, since elsewhere pytkdocs does use `inspect.getdoc`

**Comment by pawamoy** [comment]
Hi, thanks for the report :slightly_smiling_face: 

Indeed, I chose to use the `__doc__` attribute directly to avoid `inspect` populating the docstring from parent classes. But I guess I could use `inspect.cleandoc` instead of `textwrap.dedent`!

**Comment by jaredkhan** [comment]
Cool. Noticed this bug because it causes the later lines to be interpreted as code blocks. I'll open a PR :)
