### ISSUE TITLE
[BUG] Properties do not inherit superclass docstrings

### ISSUE THREAD

**Issue by jayqi** [pawamoy/pytkdocs#90]
**Describe the bug**

Properties do not properly inherit docstrings from parent class if they are not set.

**To Reproduce**

I observed this when rendering documentation using mkdocstrings. 
- Sub class with missing property docstrings: [link](https://erdantic.drivendata.org/api-reference/pydantic/#erdantic.pydantic.PydanticField)
- Super class with property docstrings defined: [link](https://erdantic.drivendata.org/api-reference/erd/#erdantic.erd.Field)

From looking at the pytokdocs source code, I think the problem is because the `get_property_documentation` method is using `inspect.getdoc` on `prop.fget` instead of `prop` directly ([link](https://github.com/pawamoy/pytkdocs/blob/a298616c2db23833b4877c67725cbbfde5a43c78/src/pytkdocs/loader.py#L632)).

Based on my experimentation below, both the property itself and `fget` work for the superclass but only the property and not `fget` work the subclass. 

```python
import inspect

class SuperClass:
    @property
    def read_only(self):
        """SuperClass.read_only docs"""
        return 0

    @property
    def mutable(self):
        """SuperClass.mutable getter docs"""
        return 0

    @mutable.setter
    def mutable(self, value):
        pass

class SubClass(SuperClass):
    @property
    def read_only(self):
        return 1

    @property
    def mutable(self):
        return 1

    @mutable.setter
    def mutable(self, value):
        pass

inspect.getdoc(SuperClass.read_only)
#> 'SuperClass.read_only docs'

inspect.getdoc(SuperClass.read_only.fget)
#> 'SuperClass.read_only docs'

inspect.getdoc(SuperClass.mutable)
#> 'SuperClass.mutable getter docs'

inspect.getdoc(SuperClass.mutable.fget)
#> 'SuperClass.mutable getter docs'


inspect.getdoc(SubClass.read_only)
#> 'SuperClass.read_only docs'

inspect.getdoc(SubClass.read_only.fget)

inspect.getdoc(SubClass.mutable)
#> 'SuperClass.mutable getter docs'

inspect.getdoc(SubClass.mutable.fget)
```

<sup>Created on 2021-02-05 by the [reprexpy package](https://github.com/crew102/reprexpy)</sup>

**Expected behavior**

Sub class properties should inherit docstrings from their parents when not set.

**System (please complete the following information):**
- pytkdocs==0.10.1
- mkdocstrings==0.14.0
- Python: 3.8.6
- OS: macOS

**Comment by pawamoy** [comment]
Hi @jayqi! Thanks a lot for the detailed report and the examples. I'll see if we can use `getdoc` on the property itself rather than its `fget` method.

**Comment by pawamoy** [comment]
Pushed a fix, will release it soon, closing!
